"""
ArcFace + FAISS face identity matching.

Each person stores up to MAX_EMBEDDINGS_PER_PERSON face embeddings (512-d vectors)
generated by ArcFace (insightface). FAISS IndexFlatIP provides fast cosine
similarity search across all enrolled embeddings in one operation.

Pipeline:
1. ArcFace converts each detected face crop -> 512-d L2-normalized embedding
2. FAISS searches against the enrolled database
3. Match above similarity threshold -> identified person
4. No match -> new person (auto-registered)

Thresholds (cosine similarity, range [0, 1], higher = more similar):
- similarity > EMA_BLEND_SIMILARITY      -> same angle, EMA-blend to adapt to drift
- MATCH_SIMILARITY_THRESHOLD < similarity < EMA_BLEND_SIMILARITY
                                         -> different angle, add as new profile
- similarity < MATCH_SIMILARITY_THRESHOLD -> new person, register fresh
"""

import json
import logging
import time
from dataclasses import dataclass, field
from datetime import date
from typing import List, Optional, Sequence, Tuple, Dict

import cv2
import numpy as np

from database import DatabaseManager
from head_pose_detector import HeadPoseDetector, HeadPose, get_pose_adjusted_threshold

logger = logging.getLogger(__name__)

# -- ArcFace / FAISS constants ------------------------------------------------
EMBEDDING_DIM = 512                      # ArcFace produces 512-d vectors

# Cosine similarity thresholds (range [0, 1], higher = more similar)
MATCH_SIMILARITY_THRESHOLD = 0.35        # minimum similarity to consider a match
EMA_BLEND_SIMILARITY      = 0.65         # above this -> same angle, blend
MAX_EMBEDDINGS_PER_PERSON  = 8


@dataclass
class FaceIdentityResult:
    """Result of identifying one detected face."""

    person_id: str
    confidence: float
    is_new: bool = False
    unknown: bool = False
    above_threshold: bool = True
    display_name: Optional[str] = None
    role: str = "guest"
    head_pose: Optional[HeadPose] = None
    pose_angles: Optional[Dict[str, float]] = None

    @property
    def is_unknown(self) -> bool:
        return self.unknown

    @property
    def is_above_threshold(self) -> bool:
        return self.above_threshold

    @property
    def is_internal(self) -> bool:
        return self.role == "internal"


@dataclass
class KnownFace:
    """Stored identity with multi-angle ArcFace embeddings."""

    person_id: str
    embeddings: List[np.ndarray]        # up to 8 x 512-d ArcFace embeddings
    display_name: Optional[str] = None
    role: str = "guest"
    pose_labels: List[str] = field(default_factory=list)
    pose_angles: List[Dict] = field(default_factory=list)


class FaceIdentityManager:
    """
    ArcFace + FAISS face identity matcher.

    Public API (unchanged from previous dlib-based implementation):
        identify(face_image) -> FaceIdentityResult
        identify_batch(face_images) -> List[FaceIdentityResult]
        compute_signature(face_image) -> Optional[str]
        compute_signature_and_match(face_image) -> tuple
    """

    CACHE_REFRESH_SECONDS = 120

    def __init__(self, db_manager: DatabaseManager):
        self._model = self._load_arcface_model()
        self.db = db_manager
        self._head_pose_detector = None

        try:
            self._head_pose_detector = HeadPoseDetector()
            logger.info("Head pose detection ENABLED")
        except Exception as e:
            logger.warning("Head pose detection disabled: %s", e)

        self._known: List[KnownFace] = self._load_known_embeddings()
        self._faiss_index = None
        self._id_map: List[Tuple[int, int]] = []   # FAISS position -> (known_idx, embedding_idx)
        self._faiss_dirty = True
        self._ensure_index_current()

        self._last_refresh_at = time.monotonic()
        total_embs = sum(len(kf.embeddings) for kf in self._known)
        logger.info(
            "Face identity cache loaded: %s persons, %s total embeddings (FAISS: %s)",
            len(self._known),
            total_embs,
            self._faiss_index.ntotal if self._faiss_index else 0,
        )

    # -- Model loading -------------------------------------------------------

    @staticmethod
    def _load_arcface_model():
        """Load ArcFace model via insightface FaceAnalysis."""
        try:
            from insightface.app import FaceAnalysis
        except ImportError:
            raise ImportError(
                "insightface is required for ArcFace embeddings. "
                "Install with: pip install insightface"
            )

        try:
            app = FaceAnalysis(
                name="buffalo_l",
                providers=["CPUExecutionProvider"],
            )
            app.prepare(ctx_id=-1, det_size=(224, 224))
            logger.info("ArcFace model (buffalo_l) loaded via FaceAnalysis")
            return app
        except Exception as e:
            raise RuntimeError(
                f"Failed to load ArcFace model: {e}. "
                "Check your internet connection for first-time download."
            ) from e

    # -- Public API ----------------------------------------------------------

    def identify_batch(
        self, face_images: Sequence[np.ndarray]
    ) -> List[FaceIdentityResult]:
        """Identify or register a batch of aligned RGB face images."""
        self._refresh_known_embeddings_if_needed()
        return [self.identify(image) for image in face_images]

    def identify(self, face_image: np.ndarray) -> FaceIdentityResult:
        """Identify an aligned RGB face image, creating a generated ID if needed."""
        embedding = self._compute_embedding(face_image)
        if embedding is None:
            return FaceIdentityResult(
                person_id="Unknown",
                confidence=0.0,
                unknown=True,
                above_threshold=False,
            )

        # Detect head pose for the incoming face
        head_pose_result = None
        pose_angles = None
        if self._head_pose_detector is not None:
            try:
                head_pose_result = self._head_pose_detector.estimate_pose(face_image)
                if head_pose_result is not None:
                    pose_angles = {
                        "yaw": head_pose_result.yaw,
                        "pitch": head_pose_result.pitch,
                        "roll": head_pose_result.roll,
                    }
            except Exception as e:
                logger.debug("Pose detection failed: %s", e)

        match = self._find_best_match(embedding, incoming_pose=head_pose_result)
        if match is not None:
            known_face, best_similarity, confidence = match
            if known_face.role != "internal":
                self._add_or_update_embedding(
                    known_face.person_id, embedding, best_similarity,
                    pose_label=head_pose_result.pose_label.value if head_pose_result else None,
                    pose_angles=pose_angles,
                )
            return FaceIdentityResult(
                person_id=known_face.person_id,
                confidence=confidence,
                is_new=False,
                display_name=known_face.display_name,
                role=known_face.role,
                head_pose=head_pose_result.pose_label if head_pose_result else None,
                pose_angles=pose_angles,
            )

        person_id = self._create_person(
            embedding,
            pose_label=head_pose_result.pose_label.value if head_pose_result else None,
            pose_angles=pose_angles,
        )
        return FaceIdentityResult(
            person_id=person_id,
            confidence=1.0,
            is_new=True,
            head_pose=head_pose_result.pose_label if head_pose_result else None,
            pose_angles=pose_angles,
        )

    def compute_signature(self, face_image: np.ndarray) -> Optional[str]:
        """Compute a serialized ArcFace embedding for uploaded reference images."""
        embedding = self._compute_embedding(face_image)
        if embedding is None:
            return None
        return self._serialize([embedding])

    def compute_signature_and_match(
        self, face_image: np.ndarray
    ) -> tuple[Optional[str], Optional[FaceIdentityResult]]:
        """Compute a reference signature and find an existing matching identity."""
        embedding = self._compute_embedding(face_image)
        if embedding is None:
            return None, None

        match = self._find_best_match(embedding)
        if match is None:
            return self._serialize([embedding]), None

        known_face, _best_similarity, confidence = match
        return self._serialize([embedding]), FaceIdentityResult(
            person_id=known_face.person_id,
            confidence=confidence,
            display_name=known_face.display_name,
            role=known_face.role,
        )

    # -- ArcFace embedding computation ---------------------------------------

    def _compute_embedding(self, face_rgb: np.ndarray) -> Optional[np.ndarray]:
        """Encode a pre-cropped RGB face into a 512-d ArcFace embedding."""
        if face_rgb is None or face_rgb.size == 0:
            return None
        if face_rgb.ndim != 3 or face_rgb.shape[2] != 3:
            return None

        # FaceAnalysis expects BGR input
        face_bgr = cv2.cvtColor(face_rgb, cv2.COLOR_RGB2BGR)

        try:
            faces = self._model.get(face_bgr)
            if not faces:
                logger.debug("FaceAnalysis did not detect a face in the crop")
                return None
            embedding = faces[0].embedding
        except Exception as e:
            logger.debug("ArcFace embedding failed: %s", e)
            return None

        if embedding is None or np.any(np.isnan(embedding)):
            return None

        result = embedding.ravel().astype(np.float32)
        if len(result) != EMBEDDING_DIM:
            logger.debug(
                "Unexpected embedding dimension: %d (expected %d)",
                len(result), EMBEDDING_DIM,
            )
            return None

        return result

    # -- FAISS index management ----------------------------------------------

    def _ensure_index_current(self):
        """Rebuild FAISS index if embeddings have changed."""
        if not self._faiss_dirty:
            return
        self._build_faiss_index()
        self._faiss_dirty = False

    def _build_faiss_index(self):
        """Build FAISS IndexFlatIP from all known embeddings."""
        try:
            import faiss
        except ImportError:
            raise ImportError(
                "faiss is required for face matching. "
                "Install with: pip install faiss-cpu"
            )

        all_embeddings = []
        self._id_map = []

        for i, known in enumerate(self._known):
            for j, emb in enumerate(known.embeddings):
                all_embeddings.append(emb)
                self._id_map.append((i, j))

        if not all_embeddings:
            self._faiss_index = None
            return

        matrix = np.array(all_embeddings, dtype=np.float32)
        faiss.normalize_L2(matrix)

        self._faiss_index = faiss.IndexFlatIP(EMBEDDING_DIM)
        self._faiss_index.add(matrix)
        logger.debug(
            "FAISS index rebuilt: %d vectors x %d dims",
            self._faiss_index.ntotal, EMBEDDING_DIM,
        )

    # -- Matching ------------------------------------------------------------

    def _find_best_match(
        self, embedding: np.ndarray, incoming_pose: Optional["PoseEstimate"] = None
    ) -> Optional[Tuple[KnownFace, float, float]]:
        """
        FAISS search for the closest match among known embeddings.

        Returns (KnownFace, cosine_similarity, confidence) or None.
        Confidence = similarity (higher = better match).
        """
        self._ensure_index_current()

        if not self._known or self._faiss_index is None or self._faiss_index.ntotal == 0:
            return None

        query = embedding.astype(np.float32).reshape(1, -1)
        try:
            import faiss
        except ImportError:
            raise ImportError(
                "faiss is required. Install with: pip install faiss-cpu"
            )
        faiss.normalize_L2(query)

        D, I = self._faiss_index.search(query, k=1)
        similarity = float(D[0][0])
        idx = int(I[0][0])

        if idx == -1 or similarity < MATCH_SIMILARITY_THRESHOLD:
            return None

        known_face_idx, emb_idx = self._id_map[idx]
        known_face = self._known[known_face_idx]

        # Pose-adjusted threshold (more lenient for different angles)
        threshold = MATCH_SIMILARITY_THRESHOLD
        if incoming_pose is not None and len(known_face.pose_labels) > emb_idx:
            stored_pose_label = known_face.pose_labels[emb_idx]
            try:
                stored_pose = HeadPose(stored_pose_label)
                # Convert L2 distance leniency factor -> similarity leniency factor
                dist_threshold = get_pose_adjusted_threshold(
                    stored_pose, incoming_pose.pose_label,
                    base_threshold=0.60,
                )
                leniency = dist_threshold / 0.60  # e.g., 1.15 = 15% more lenient
                threshold = MATCH_SIMILARITY_THRESHOLD / leniency
            except (ValueError, AttributeError):
                pass

        if similarity < threshold:
            return None

        return known_face, similarity, float(similarity)

    # -- Database / persistence ----------------------------------------------

    def _load_known_embeddings(self) -> List[KnownFace]:
        """Load known persons and their ArcFace embeddings from the database."""
        result = []
        for person in self.db.get_all_persons():
            sig = person["face_signature"]
            embeddings = self._deserialize(sig)
            if embeddings:
                result.append(KnownFace(
                    person_id=person["person_id"],
                    embeddings=embeddings,
                    display_name=person["display_name"],
                    role=person["role"] or "guest",
                ))
        return result

    def _refresh_known_embeddings_if_needed(self):
        """Periodically reload known embeddings from the database."""
        now = time.monotonic()
        if now - self._last_refresh_at < self.CACHE_REFRESH_SECONDS:
            return
        self._known = self._load_known_embeddings()
        self._faiss_dirty = True
        self._last_refresh_at = now
        logger.debug(
            "Face identity cache refreshed: %s persons",
            len(self._known),
        )

    def _create_person(
        self,
        embedding: Optional[np.ndarray],
        pose_label: Optional[str] = None,
        pose_angles: Optional[Dict] = None,
    ) -> str:
        """Create a new person with their initial ArcFace embedding."""
        serialized = (
            self._serialize([embedding]) if embedding is not None else None
        )
        for _ in range(5):
            person_id = self.db.get_next_face_id(date.today())
            if self.db.add_person(person_id, serialized):
                if embedding is not None:
                    self._known.append(KnownFace(
                        person_id=person_id,
                        embeddings=[embedding],
                        pose_labels=[pose_label] if pose_label else ["unknown"],
                        pose_angles=[pose_angles] if pose_angles else [{}],
                    ))
                    self._faiss_dirty = True
                logger.info(
                    "Registered new face ID: %s (initial pose: %s)",
                    person_id, pose_label or "unknown",
                )
                return person_id
        raise RuntimeError("Could not allocate a unique face ID")

    def _add_or_update_embedding(
        self,
        person_id: str,
        new_embedding: np.ndarray,
        best_similarity: float,
        pose_label: Optional[str] = None,
        pose_angles: Optional[Dict] = None,
    ) -> None:
        """
        Update in-memory embeddings for a matched person.

        - High similarity (>= EMA_BLEND_SIMILARITY): EMA-blend the closest embedding
        - Moderate similarity (between thresholds): store as new angle profile
        """
        for known_face in self._known:
            if known_face.person_id != person_id:
                continue

            if best_similarity >= EMA_BLEND_SIMILARITY:
                # Same angle -- find closest stored embedding and blend
                stored = np.array(known_face.embeddings, dtype=np.float32)
                sims = stored @ new_embedding
                idx = int(np.argmax(sims))
                alpha = 0.1
                known_face.embeddings[idx] = (
                    (1.0 - alpha) * known_face.embeddings[idx]
                    + alpha * new_embedding
                )
                # Re-normalize after blending
                known_face.embeddings[idx] /= np.linalg.norm(known_face.embeddings[idx])
                self._faiss_dirty = True
            else:
                # Different angle -- append as new profile
                if len(known_face.embeddings) < MAX_EMBEDDINGS_PER_PERSON:
                    known_face.embeddings.append(new_embedding)
                    known_face.pose_labels.append(pose_label or "unknown")
                    known_face.pose_angles.append(pose_angles or {})
                    self._faiss_dirty = True
                    logger.debug(
                        "Added new angle profile for %s (pose=%s, total=%s embeddings)",
                        person_id, pose_label, len(known_face.embeddings),
                    )
            break

    # -- Serialization -------------------------------------------------------

    @staticmethod
    def _serialize(embeddings: List[np.ndarray]) -> str:
        """Store multiple embeddings as a JSON array of lists."""
        data = [emb.tolist() for emb in embeddings]
        return json.dumps(data, separators=(",", ":"))

    @staticmethod
    def _deserialize(signature: Optional[str]) -> List[np.ndarray]:
        """
        Load stored embeddings.

        Supports:
          - [[512 floats], ...]  -> List[ndarray]  (ArcFace multi-angle, current)
          - [[128 floats], ...]  -> silently dropped (legacy dlib, incompatible dim)
          - [128 floats]         -> [ndarray]      (legacy single dlib, dropped)
        """
        if not signature:
            return []
        try:
            data = json.loads(signature)
            if not isinstance(data, list) or not data:
                return []

            # Legacy single-embedding: first element is a float
            if isinstance(data[0], (int, float)):
                if len(data) == EMBEDDING_DIM:
                    return [np.array(data, dtype=np.float32)]
                return []  # 128-d legacy, incompatible

            # Multi-embedding: first element is a list
            if isinstance(data[0], list):
                result = []
                for arr in data:
                    if isinstance(arr, list) and len(arr) == EMBEDDING_DIM:
                        result.append(np.array(arr, dtype=np.float32))
                return result
            return []
        except (json.JSONDecodeError, ValueError):
            pass
        return []
